name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - tsm-jekyll-upgrade

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true
      - name: Build jekyll
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/../jekyll_build
          cd $GITHUB_WORKSPACE/../jekyll_build
          git clone https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git .
          git switch -c $remote_branch
          touch .nojekyll
          bundle exec jekyll build -s $GITHUB_WORKSPACE -d $GITHUB_WORKSPACE/../jekyll_build
          git config user.name "$GITHUB_ACTOR" && \
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && \
          git add . && \
          git commit --allow-empty -m "jekyll build from Action $GITHUB_SHA" && \
          git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git $remote_branch:$remote_branch
        env:
          remote_branch: tsm-jekyll-upgrade-out
