name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - tsm-jekyll-upgrade

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true
      - name: Install dependency
        run: sudo apt-get install jq
      - name: Build + Deploy Jekyll
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/../jekyll_build
          cd $GITHUB_WORKSPACE/../jekyll_build
          git clone https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git .
          git switch -c $remote_branch
          git branch --set-upstream-to=origin/$remote_branch $remote_branch
          git pull
          cd $GITHUB_WORKSPACE
          export BASE_URL=$(curl -H "Accept: application/vnd.github.v3+json" https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/$GITHUB_REPOSITORY/pages | jq -r .source.path)
          echo "Base URL: $BASE_URL"
          curl -H "Accept: application/vnd.github.v3+json" https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/$GITHUB_REPOSITORY/pages
          bundle exec jekyll build -b $BASE_URL -s $GITHUB_WORKSPACE -d $GITHUB_WORKSPACE/../jekyll_build
          cd $GITHUB_WORKSPACE/../jekyll_build
          touch .nojekyll
          git config user.name "$GITHUB_ACTOR" && \
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && \
          git add . && \
          git commit --allow-empty -m "jekyll build from Action $GITHUB_SHA" && \
          git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git $remote_branch:$remote_branch
        env:
          remote_branch: tsm-jekyll-upgrade-out
